# -*- coding: utf-8 -*-
"""DeepFake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXbFPkyJ_D_446mbsqJHiMI8RQgSQqlM
"""

# pip install transformers pillow (handled in requirements)

from transformers import pipeline
from PIL import Image

# 1. Load the Two Brains
print("Loading Brain 1 (Face Swap Expert)...")
pipe_swap = pipeline("image-classification", model="dima806/deepfake_vs_real_image_detection")

print("Loading Brain 2 (GenAI Expert)...")
pipe_gen = pipeline("image-classification", model="Organika/sdxl-detector")

def scan_image(image_path):
    try:
        img = Image.open(image_path)
        print(f"\nScanning image: {image_path}...")

        # --- BRAIN 1 ANALYSIS (Face Swaps) ---
        result_swap = pipe_swap(img)
        score_swap = 0
        # Check if it finds 'fake' or 'ai'
        for r in result_swap:
            if r['label'].lower() in ['fake', 'ai', 'artificial']:
                score_swap = r['score']

        # --- BRAIN 2 ANALYSIS (Generated Art) ---
        result_gen = pipe_gen(img)
        score_gen = 0
        # Check if it finds 'artificial' or 'computer'
        for r in result_gen:
             if r['label'].lower() in ['artificial', 'fake']:
                score_gen = r['score']

        # --- THE REPORT ---
        print("\n" + "="*40)
        print("     MULTI-MODEL DETECTION REPORT")
        print("="*40)

        print(f"Brain 1 (Swap Expert) Fake Score: {score_swap*100:.2f}%")
        print(f"Brain 2 (GenAI Expert) Fake Score: {score_gen*100:.2f}%")

        print("-" * 40)

        # FINAL VERDICT
        # If either brain is confident (>50%), we call it FAKE.
        if score_swap > 0.5 or score_gen > 0.5:
            print(">>> FINAL VERDICT: FAKE / AI GENERATED <<<")
        else:
            print(">>> FINAL VERDICT: REAL IMAGE <<<")

        print("="*40 + "\n")

    except Exception as e:
        print(f"Error: {e}")

# Run the scan on the uploaded file
# scan_image("test.jpg")  # Disabled for script execution
# pip install gradio (handled in requirements)

import gradio as gr
from transformers import pipeline
from PIL import Image

# Initialize the brains once
print("Initializing AI Models...")
pipe_swap = pipeline("image-classification", model="dima806/deepfake_vs_real_image_detection")
pipe_gen = pipeline("image-classification", model="Organika/sdxl-detector")

def detect_deepfake(image):
    try:
        # Brain 1: Face Swap
        res_swap = pipe_swap(image)
        score_swap = 0
        for r in res_swap:
            if r['label'].lower() in ['fake', 'ai', 'artificial']:
                score_swap = r['score']

        # Brain 2: Diffusion/GenAI
        res_gen = pipe_gen(image)
        score_gen = 0
        for r in res_gen:
             if r['label'].lower() in ['artificial', 'fake']:
                score_gen = r['score']

        # Calculate Final Verdict
        final_verdict = "REAL"
        color = "green"

        if score_swap > 0.5 or score_gen > 0.5:
            final_verdict = "FAKE / AI GENERATED"
            color = "red"

        # Return text for the UI
        return (f"VERDICT: {final_verdict}\n\n"
                f"Swap Score: {score_swap*100:.2f}%\n"
                f"GenAI Score: {score_gen*100:.2f}%")
    except Exception as e:
        return f"Error: {e}"

# Build the Interface
interface = gr.Interface(
    fn=detect_deepfake,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="Deepfake Detection Tool",
    description="Upload an image to check if it's Real or AI Generated."
)

# Launch it
interface.launch()