
"""DeepFake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXbFPkyJ_D_446mbsqJHiMI8RQgSQqlM
"""



from transformers import pipeline
from PIL import Image

# 1. Load the Two Brains
print("Loading Brain 1 (Face Swap Expert)...")
pipe_swap = pipeline("image-classification", model="dima806/deepfake_vs_real_image_detection")

print("Loading Brain 2 (GenAI Expert)...")
pipe_gen = pipeline("image-classification", model="Organika/sdxl-detector")

def scan_image(image_path):
    try:
        img = Image.open(image_path)
        print(f"\nScanning image: {image_path}...")

        # --- BRAIN 1 ANALYSIS (Face Swaps) ---
        result_swap = pipe_swap(img)
        score_swap = 0
        # Check if it finds 'fake' or 'ai'
        for r in result_swap:
            if r['label'].lower() in ['fake', 'ai', 'artificial']:
                score_swap = r['score']

        # --- BRAIN 2 ANALYSIS (Generated Art) ---
        result_gen = pipe_gen(img)
        score_gen = 0
        # Check if it finds 'artificial' or 'computer'
        for r in result_gen:
             if r['label'].lower() in ['artificial', 'fake']:
                score_gen = r['score']

        # --- THE REPORT ---
        print("\n" + "="*40)
        print("     MULTI-MODEL DETECTION REPORT")
        print("="*40)

        print(f"Brain 1 (Swap Expert) Fake Score: {score_swap*100:.2f}%")
        print(f"Brain 2 (GenAI Expert) Fake Score: {score_gen*100:.2f}%")

        print("-" * 40)

        # FINAL VERDICT
        # If either brain is confident (>50%), we call it FAKE.
        if score_swap > 0.5 or score_gen > 0.5:
            print(">>> FINAL VERDICT: FAKE / AI GENERATED <<<")
        else:
            print(">>> FINAL VERDICT: REAL IMAGE <<<")

        print("="*40 + "\n")

    except Exception as e:
        print(f"Error: {e}")

# Run the scan on the uploaded file (commented out)
# scan_image("test.jpg")



import gradio as gr
from transformers import pipeline
from PIL import Image

# --- 1. BACKEND (The Brains) ---
print("Initializing System...")
print("Loading Brain 1 (Face Swap Expert - dima806)...")
pipe_swap = pipeline("image-classification", model="dima806/deepfake_vs_real_image_detection")

print("Loading Brain 2 (GenAI Expert - Organika)...")
pipe_gen = pipeline("image-classification", model="Organika/sdxl-detector")
print("System Ready.")

def detect_deepfake(image):
    if image is None:
        return "⚠️ Please upload an image first."

    try:
        # --- BRAIN 1 ANALYSIS ---
        res_swap = pipe_swap(image)
        score_swap = 0
        for r in res_swap:
            if r['label'].lower() in ['fake', 'ai', 'artificial']:
                score_swap = r['score']

        # --- BRAIN 2 ANALYSIS ---
        res_gen = pipe_gen(image)
        score_gen = 0
        for r in res_gen:
             if r['label'].lower() in ['artificial', 'fake']:
                score_gen = r['score']

        # --- COMBINED LOGIC ---
        final_confidence = max(score_swap, score_gen)

        # Determine Verdict
        if final_confidence > 0.5: # 50% Threshold
            verdict_text = "🚨 FAKE / AI GENERATED"
        else:
            verdict_text = "✅ REAL IMAGE"

        # RETURN ONLY THE VERDICT TEXT
        return verdict_text

    except Exception as e:
        return f"Error: {str(e)}"

# --- 2. FRONTEND UI DESIGN (The Dashboard) ---
custom_css = """
/* Main background */
body, .gradio-container {
    background-color: #f0f2f6 !important;
    font-family: 'Arial', sans-serif;
}

/* Force light theme on Gradio components */
.gr-box, .gr-input, .gr-button, .gr-textbox, .gr-image {
    background-color: white !important;
    border-color: #e2e8f0 !important;
}

/* Styling for main titles */
h1, h2, h3 {
    color: #1a202c !important;
}

/* FORCE BLACK TEXT ON SPECIFIC ELEMENTS */

/* 1. System Status Text */
.status-indicator, .status-indicator p {
    color: #000000 !important; /* Pure Black */
    font-weight: bold;
}

/* 2. Blue "How to Use" Box - ALL TEXT BLACK */
.guide-box, .guide-box h3, .guide-box li, .guide-box b, .guide-box p {
    background-color: #ebf8ff !important;
    color: #000000 !important; /* Pure Black */
    padding: 10px;
    border-radius: 8px;
    border: 1px solid #bee3f8;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

/* 3. Red "Scam Alert" Box  */
.scam-alert, .scam-alert h3, .scam-alert li, .scam-alert b, .scam-alert p {
    background-color: #fff5f5 !important;
    color: #000000 !important; /* Pure Black */
    padding: 10px;
    border-radius: 8px;
    border: 1px solid #fed7d7;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

/* 4. Footer Text */
.footer-text, .footer-text p, .footer-text i {
    color: #000000 !important; /* Pure Black */
    text-align: center;
}

/* Spacing for lists */
.guide-box li, .scam-alert li {
    margin-bottom: 6px;
}
"""

with gr.Blocks(css=custom_css) as app:

    # --- HEADER SECTION ---
    with gr.Row():
        with gr.Column(scale=3):
            gr.Markdown("# 🕵️‍♂️ DeepFake Detection")
            gr.Markdown("### Powered by Ensemble Learning")
        with gr.Column(scale=1):
            gr.Markdown("✅ SYSTEM STATUS:\n\n🟢 Models Loaded & Ready to Detect", elem_classes=["status-indicator"])

    gr.Markdown("---")

    # --- MAIN CONTENT ---
    with gr.Row():

        # LEFT COLUMN: The Tool
        with gr.Column(scale=2):
            gr.Markdown("### 📸 Image Evaluation")
            input_image = gr.Image(type="pil", label="Upload Image Here", height=300)

            with gr.Row():
                clear_btn = gr.ClearButton(components=[input_image], value="CLEAR")
                submit_btn = gr.Button("🔍 SCAN IMAGE", variant="primary", size="lg")

            # BIGGER OUTPUT SECTION
            gr.Markdown("### 📊 Detection Results")
            with gr.Group():
                # REMOVED CONFIDENCE BOX
                output_verdict = gr.Textbox(label="Final Verdict", lines=1, elem_classes=["verdict-box"])

        # RIGHT COLUMN: Education & Awareness
        with gr.Column(scale=1):

            # How to Use
            gr.Markdown(
                """
                <div class="guide-box">
                <h3>📘 How it Works:-</h3>
                <ol>
                    <li><b>Upload:</b> Drop or Upload an image into the box.</li>
                    <li><b>Scan:</b> Click the Orange "Scan Image" button.</li>
                    <li><b>Analyze:</b> Check the Verdict.</li>
                </ol>
                </div>
                """
            )

            gr.HTML("<br>")

            # Awareness Section
            gr.Markdown(
                """
                <div class="scam-alert">
                <h3>⚠️ Common Deepfake Frauds:-</h3>
                <ul>
                    <li>🔴 <b>CEO Fraud:</b> Scammers use deepfake audio/images of bosses to demand money transfers.</li>
                    <li>🔴 <b>Romance Scams:</b> Fake video calls using AI faces to trick victims in relationships.</li>
                    <li>🔴 <b>Extortion:</b> Creating fake compromising photos to blackmail victims.</li>
                    <li>🔴 <b>Fake News:</b> Generating realistic photos of politicians to spread lies.</li>
                </ul>
                </div>
                """
            )

    # --- WIRING ---
    submit_btn.click(
        fn=detect_deepfake,
        inputs=input_image,
        outputs=output_verdict
    )

app.launch()